version: 1
formatters:
  lorumFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  lorumHandler:
    formatter: lorumFormatter
    class: logging.StreamHandler
loggers:
  langmodel:
    handlers: ["lorumHandler"]
    level: INFO
  server:
    handlers: ["lorumHandler"]
    level: INFO
